# Generated by Django 2.1.5 on 2019-02-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Group Name')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Group Descritption')),
                ('image', models.ImageField(upload_to='group_images/')),
            ],
        ),
    ]
