# Generated by Django 2.1.5 on 2019-02-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=100, verbose_name='Student Name')),
                ('student_designation', models.CharField(default='', max_length=100, verbose_name='Student Designation')),
                ('photo', models.ImageField(upload_to='user_images/')),
            ],
        ),
    ]
