# Generated by Django 2.1.5 on 2019-02-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190209_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(upload_to='domain_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='groupevents',
            name='event_description',
            field=models.TextField(default='', max_length=1000, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='groupevents',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pages.Groups'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pages.Groups'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Group Descritption'),
        ),
    ]
