# Generated by Django 2.1.5 on 2019-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190211_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
