# Generated by Django 2.1.5 on 2019-02-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190211_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
        migrations.AddField(
            model_name='groups',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
    ]
