# Generated by Django 2.1.5 on 2019-02-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_groups_web_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=100, verbose_name='Event Name')),
                ('project_description', models.TextField(default='', max_length=1000, verbose_name='Event Description')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pages.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='groupevents',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevents',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='groupevents',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Event Location'),
        ),
    ]
