# Generated by Django 2.1.5 on 2019-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190213_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevents',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupevents',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
