# Generated by Django 2.1.5 on 2019-02-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190213_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevents',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
