# Generated by Django 2.1.5 on 2019-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190213_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevents',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
