# Generated by Django 2.1.5 on 2019-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190213_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='email',
            field=models.EmailField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
