# Generated by Django 2.1.5 on 2019-02-27 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190218_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='Group Descritption'),
        ),
        migrations.AddField(
            model_name='groupheader',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header', to='pages.Groups'),
        ),
    ]
