# Generated by Django 2.1.5 on 2019-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20190227_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupheader',
            name='description',
            field=models.CharField(default='', max_length=500000),
        ),
        migrations.AlterField(
            model_name='groupheader',
            name='title',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
