# Generated by Django 2.1.5 on 2019-02-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20190227_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('desciptiom', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='home_project_images/')),
            ],
        ),
    ]
