# Generated by Django 2.1.5 on 2020-03-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_homeproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevents',
            name='event_description',
            field=models.TextField(default='', max_length=10000, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='groupheader',
            name='description',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='groupheader',
            name='title',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='groupproject',
            name='project_description',
            field=models.TextField(default='', max_length=10000, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='Group Descritption'),
        ),
    ]
