# Generated by Django 2.1.5 on 2019-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('des', models.CharField(blank=True, max_length=200, null=True)),
                ('ver', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_type', models.CharField(blank=True, choices=[('Self', 'Self'), ('Dept', 'Dept'), ('STC', 'STC'), ('Org', 'Org'), ('Sece', 'Sece')], max_length=200, null=True)),
                ('generated_certi', models.FileField(max_length=1000, upload_to='certi/')),
            ],
        ),
    ]
